### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fivetanley** [andrew-d/static-binaries#17]
Hi. What is the license this code is provided under? I couldn't find one in the repository.

**Comment by John3** [comment]
This: https://choosealicense.com/no-permission/ and close the issue?

**Comment by andrew-d** [comment]
Created a `LICENSE` file in 0be803093b7d4b627b4d4eddd732e54ac4184b67 - I chose The Unlicense for everything other than the binaries, which are released under their respective licenses.
